import { NextRequest, NextResponse } from 'next/server';
import { and, eq } from 'drizzle-orm';
import { db } from '@/db';
import { inbodyScans } from '@/db/schema';
import { requireUser } from '@/lib/auth';
import { fail } from '@/lib/http';
import { z } from 'zod';
const config=()=>{const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,bucket=process.env.SUPABASE_INBODY_BUCKET??'inbody-private';if(!url||!key)throw new Error('Supabase Storage is not configured');return {url:url.replace(/\/$/,''),key,bucket};};
const fields=z.object({measuredAt:z.iso.date(),weightKg:z.coerce.number().min(25).max(400),bodyFatPercent:z.coerce.number().min(1).max(75).optional(),skeletalMuscleKg:z.coerce.number().min(1).max(200).optional(),fatMassKg:z.coerce.number().min(0).max(300).optional(),measuredBmr:z.coerce.number().int().min(500).max(6000).optional()});
export async function POST(request:NextRequest){try{const userId=await requireUser();const {url,key,bucket}=config();const data=await request.formData();const file=data.get('file');if(!(file instanceof File))throw new Error('Choose an image or PDF');const allowed=['application/pdf','image/jpeg','image/png','image/heic'];if(!allowed.includes(file.type)||file.size>5_000_000||file.size===0)throw new Error('PDF/JPEG/PNG/HEIC up to 5 MB only');const input=fields.parse(Object.fromEntries(['measuredAt','weightKg','bodyFatPercent','skeletalMuscleKg','fatMassKg','measuredBmr'].filter(k=>data.get(k)!==null&&data.get(k)!=='').map(k=>[k,data.get(k)])));const ext=file.type==='application/pdf'?'pdf':file.type==='image/png'?'png':file.type==='image/heic'?'heic':'jpg';const path=`${userId}/${crypto.randomUUID()}.${ext}`;const endpoint=`${url}/storage/v1/object/${bucket}/${path}`;const upload=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${key}`,apikey:key,'Content-Type':file.type,'x-upsert':'false'},body:Buffer.from(await file.arrayBuffer())});if(!upload.ok)throw new Error('Report upload failed');try{const [scan]=await db.insert(inbodyScans).values({userId,measuredAt:input.measuredAt,weightKg:String(input.weightKg),bodyFatPercent:input.bodyFatPercent?.toString(),skeletalMuscleKg:input.skeletalMuscleKg?.toString(),fatMassKg:input.fatMassKg?.toString(),measuredBmr:input.measuredBmr,attachmentKey:path}).returning();return NextResponse.json({scan});}catch(e){await fetch(endpoint,{method:'DELETE',headers:{Authorization:`Bearer ${key}`,apikey:key}}).catch(()=>{});throw e;}}catch(e){return fail(e)}}
export async function GET(request:NextRequest){try{const userId=await requireUser();const scanId=z.uuid().parse(request.nextUrl.searchParams.get('scanId'));const [scan]=await db.select().from(inbodyScans).where(and(eq(inbodyScans.id,scanId),eq(inbodyScans.userId,userId)));if(!scan?.attachmentKey)throw new Error('NOT_FOUND');const {url,key,bucket}=config();const r=await fetch(`${url}/storage/v1/object/sign/${bucket}/${scan.attachmentKey}`,{method:'POST',headers:{Authorization:`Bearer ${key}`,apikey:key,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:60})});if(!r.ok)throw new Error('Could not open report');const result=await r.json() as {signedURL:string};return NextResponse.json({url:`${url}/storage/v1${result.signedURL}`});}catch(e){return fail(e)}}
